### ISSUE TITLE
What ore dict name do you use

### ISSUE THREAD

**Issue by tyler489** [RCXcrafter/AOBDorechunks#10]
Is it like IronChunk or Ironchunk  or Ironchunk or something else

**Comment by RCXcrafter** [comment]
All the chunks are automatically registered as chunkIron etc. They are also registered as oreIron etc. by default but this can be changed to dustIron, clumpIron or any other name.

**Comment by tyler489** [comment]
Doesnt oredictioniing them as oreIron allow you to use a mod to convert them back to ore... for infinate resources?

**Comment by RCXcrafter** [comment]
There are mods that allow you to do that, but most of them have an option to blacklist certain items. There are of course mods that don't have a blacklist, so that's why I added an option to change it.

**Comment by tyler489** [comment]
Thereason i came was because i had a request for your chunks to be supported in enderio. How would you like it to be done. I can either make your chunks process in the sagmill and allow doubleing. Or i can have them process in the alloy smelter and just smelt. Your choice.

**Comment by RCXcrafter** [comment]
I took a look and it seems ender io machines can process my ore chunks just fine. But to answer your question, by default they are supposed to be doubled in crusher type machines, but this can be changed in the config by changing the oredict prefix (to dust for example).

**Comment by tyler489** [comment]
Yes they can as long as they use oreOrename but we had multiple people request support for chunkOrename

**Comment by RCXcrafter** [comment]
Well in that case I guess, go with the doubling. Unless you think that's not balanced, I don't use enderIO much at all. (I don't really mind but if you need me to choose, that's my choice)

**Comment by RCXcrafter** [comment]
I made a mistake, the oredict name I'm using is actually oreChunkOrename, but you might have noticed that already.

**Comment by tyler489** [comment]
Eio is smart i can just call ChunkOrename and it knoes thats oredict
