### ISSUE TITLE
Default oredic changed?

### ISSUE THREAD

**Issue by Akitori** [RCXcrafter/AOBDorechunks#11]
Hiya! Wanted to ask if you could change your default oredic from ore to cluster instead! Main reason being, this prevents people from infinite duping with your mod by default.

**Comment by RCXcrafter** [comment]
I decided to use ore because most mods that allow the duping have a blacklist that you can add the orechunks to. And if that's not possible you can still manually change it to whatever you like. It's mostly up to the modpack maker to decide.
