### ISSUE TITLE
OreDictionary support and Crafttweaker integration

### ISSUE THREAD

**Issue by kragnoth** [RCXcrafter/AOBDorechunks#13]
Crafttweaker can iterate through all members of an ore dictionary group. However, it seems like the oredictionary is initialized in a stage after CrT runs scripts.

Would it be possible to move the oredict generation of this mod up the pipeline, or is that not possible due to the way the ore chunks are generated?

Thanks

**Comment by RCXcrafter** [comment]
Unfortunately it won't be possible with crafttweaker but there are other mods that can register oredict entries early enough. https://minecraft.curseforge.com/projects/ore-dictionary-initializer https://minecraft.curseforge.com/projects/unidict and there are probably more

**Comment by RCXcrafter** [comment]
Sorry, I wasn't paying attention and I thought you wrote something else.
As far as I know crafttweaker runs scripts really late but maybe that changed. I don't think I can do anything about this unfortunately.

**Comment by kragnoth** [comment]
You have a script in your code that adds CrT functionality.  I was able to tie into that.  Close this tracker if it is not useful to you.

**Comment by RCXcrafter** [comment]
Oredict registry has been moved to preInit, I'm not sure why I didn't do this earlier but I did it now.
