### ISSUE TITLE
Cobalt and Ardite chunks don't display correctly

### ISSUE THREAD

**Issue by Doomathon** [RCXcrafter/AOBDorechunks#14]
Using version 1.12.2 - 1.0.9

Expected behavior: Cobalt and Ardite Chunks should display with a nether-y stone backdrop for the colored overlay.

Observed behavior: Cobalt and Ardite Chunks actually display with the identical stone backdrop as for overworld ores.

I imagine this extends to other nether ores from other mods, not just Tinker's Construct ores. The stone type for both in the config reads:
S:stoneType=nether

so that part at least functions correctly. As a visual bug this is fairly minor, since all the chunks function as expected in game, but it'd be nice if this got fixed.

**Comment by RCXcrafter** [comment]
I removed this feature from the 1.12.2 port because everything had to work with item models and you can't just set a different texture like in 1.7.10 but I might be able to re-add it.
