### ISSUE TITLE
Fortune Levels above 3 seem to do nothing

### ISSUE THREAD

**Issue by brisingraerowing** [RCXcrafter/AOBDorechunks#16]
I have Fortune 24 (thanks to Apotheosis), and I got one chunk per ore for some reason (using iron). I mined 8 stacks of Iron, and got 8 stacks of chunks.

**Comment by RCXcrafter** [comment]
That sounds about right, fortune is not as effective on ore chunk drops as it is on coal or diamond to prevent it from being overpowered when another mod gives players ridiculous levels of fortune. It's also very random (for vanilla drops too), even with a very high level there's still a chance you only get one drop.
