### ISSUE TITLE
Ore dict resolution crash with tinkers construct slime grass

### ISSUE THREAD

**Issue by kragnoth** [RCXcrafter/AOBDorechunks#4]
1.06 version of the mod
1.12.2 minecraft
2503 forge

I was randomly swinging around with an instant dig pickaxe and got this crash:

https://pastebin.com/Ur69wvAe

I think I traced it to the tconstruct block that corresponds to the slime fern.  Not 100% sure

Maybe change it so the oreswapper method only runs on blocks and not tile entities?

**Comment by RCXcrafter** [comment]
I can't reproduce this crash but I'm pretty sure I know what's causing this, please try using this version to see if that fixes it https://github.com/RCXcrafter/AOBDorechunks/releases/download/1.0.6-maybefix/AOBDOC-1.12.2-1.0.6.jar

**Comment by kragnoth** [comment]
Thanks, I'll try that as soon as I get back on my home computer.

**Comment by kragnoth** [comment]
Seems to be when I veinminer slime dirt from tinkers construct, and the grasses and ferns on top break.

**Comment by RCXcrafter** [comment]
okay, I was able to reproduce the crash with veinminer and I fixed it. I will upload it to curse soon.

**Comment by kragnoth** [comment]
Thanks!
