### ISSUE TITLE
Astral Sorcery Celestial Crystal Clusters drop starmetal ore chunks

### ISSUE THREAD

**Issue by Entayan** [RCXcrafter/AOBDorechunks#6]
Celestial crystal clusters are supposed to drop celestial crystals and yet they drop starmetal ore chunks. This means that there is no way to get celestial crystals. Could celestial crystal clusters be excepted from the list of ores to drop chunks? On a somewhat related note, would it be possible to create a config file like fortune ores to fix things like this?

**Comment by RCXcrafter** [comment]
I'm not having this issue in any minecraft version, can you give me some more information on what versions you're using?

**Comment by Entayan** [comment]
I'm in MC 1.12.2 using 1.0.7 of JAOPCA ore chunks and version 1.8.3 of Astral Sorcery. Is there any other helpful information that I can give you?

**Comment by RCXcrafter** [comment]
Alright I fixed it, I'll upload a new release now

**Comment by Entayan** [comment]
Thanks!
