### ISSUE TITLE
Redstone Drops

### ISSUE THREAD

**Issue by Mikeagan** [RCXcrafter/AOBDorechunks#7]
Currently the mod breaks Redstone Drops. When Mining Redstone Ore or Breaking Redstone wire, nothing drops. It does not matter which tool is used. This makes it so that you can not get Redstone in your inventory with this mod, and therefore it can not be used. using MC 1.12.2 Forge-1.12.2-14.23.1.2555

**Comment by RCXcrafter** [comment]
I was a bit too quick with the previous release, it's fixed in v1.0.9
